---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    autoremove: true
    update_cache: true
  loop:
    - git
    - python3-jsonpatch
    - python3-kubernetes
    - python3-yaml

- name: Download archive
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-arm64.tar.gz
    checksum: sha256:https://get.helm.sh/helm-{{ helm_version }}-linux-arm64.tar.gz.sha256sum
    dest: /tmp
    owner: root
    group: root
    mode: "644"
  notify: Install binary

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Delete archive
  ansible.builtin.file:
    path: /tmp/helm-{{ helm_version }}-linux-arm64.tar.gz
    state: absent

- name: Install diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
