---
# - name: Cluster Provisioning
#   hosts: cluster
#   become: true
#   gather_facts: true
#   roles:
#     - role: cluster

- name: Control Plane Provisioning
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: control
  serial: 1

# - name: Node Provisioning
#   hosts: node
#   become: true
#   gather_facts: true
#   roles:
#     - role: node
