---
- name: Cluster deployment
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - role: download
    - role: raspberrypi

- name: Control plane deployment
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: k3s/control

- name: Node deployment
  hosts: node
  become: true
  gather_facts: true
  roles:
    - role: k3s/node
