---
- name: Cluster Deployment
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - role: validation
    - role: user
      when: raspberry_pi | default(false)
    - role: os
      when: raspberry_pi | default(false)

# - name: Control Plane Deployment
#   hosts: control
#   become: true
#   gather_facts: true
#   roles:
#     - role: k3s/download
#     - role: k3s/control
#   serial: 1

# - name: Node Deployment
#   hosts: node
#   become: true
#   gather_facts: true
#   roles:
#     - role: k3s/download
#     - role: k3s/node
