---
- name: Distribution Upgrade
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Set distribution
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: "bullseye"
        replace: "bookworm"
      loop:
        - /etc/apt/sources.list
        - /etc/apt/sources.list.d/raspi.list
