---
- name: Cluster Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  pre_tasks:
    - name: Validate password
      ansible.builtin.assert:
        that:
          - smtp_password | length > 11
          - smtp_password == smtp_password_check
        fail_msg: Passwords don't match or less than 12 characters
        quiet: true
  vars_prompt:
    - name: disk_trim
      prompt: Trim SSD disks? [Y/n]
      default: 'n'
      private: false
    - name: smtp_password
      prompt: Enter SMTP server password
      unsafe: true
    - name: smtp_password_check
      prompt: Retype password
      unsafe: true
  roles:
    - role: cluster

- name: Kubernetes Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - role: helm
    - role: k3s
  serial:
    - 1
    - 2
    - 5

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  roles:
    - role: cilium
    - role: certmanager
    - role: longhorn
    - role: prometheus
    # - role: sealedsecrets
