---
- name: Cluster Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  vars_prompt:
    - name: trim_disks
      prompt: Trim SSD disks? [Y/n]
      default: 'n'
      private: false
  roles:
    - role: cluster

- name: Kubernetes Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - role: helm
    - role: k3s
  serial:
    - 1
    - 2
    - 5

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  roles:
    - role: cilium
    - role: certmanager
    - role: longhorn
    - role: prometheus
    # - role: sealedsecrets
