---
- name: Cluster Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - role: cluster
  tags:
    - cluster

- name: Control Plane Provisioning
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: control
  serial: 1
  tags:
    - control

- name: Node Provisioning
  hosts: node
  become: true
  gather_facts: true
  roles:
    - role: node
  tags:
    - node

- name: Charts Provisioning
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: cilium
    - role: certmanager
    - role: longhorn
    - role: prometheus
  tags:
    - charts
