---
- name: Cluster Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - role: cluster
  tags:
    - cluster

- name: Server Provisioning
  hosts: server
  become: true
  gather_facts: true
  roles:
    - role: server
  serial: 1
  tags:
    - server

- name: Node Provisioning
  hosts: node
  become: true
  gather_facts: true
  roles:
    - role: node
  tags:
    - node

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  roles:
    - role: cilium
    - role: certmanager
    - role: longhorn
    - role: prometheus
  tags:
    - charts
