---
- name: Node Reset
  hosts: cerus.lan
  gather_facts: true
  become: true
  tasks:
    - name: Perform node reset
      ansible.builtin.import_role:
        name: common
        tasks_from: reset
