---
- name: Reset Control Plane
  hosts: control
  become: true
  gather_facts: true
  tasks:
    - name: Remove helm repository
      kubernetes.core.helm_repository:
        name: '{{ item }}'
        repo_state: absent
      loop:
        - cilium
        - jetstack
        - longhorn
        - prometheus

    - name: Reset k3s
      ansible.builtin.import_role:
        name: k3s
        tasks_from: reset

    - name: Reset cilium
      ansible.builtin.import_role:
        name: cilium
        tasks_from: reset

    - name: Reset helm
      ansible.builtin.import_role:
        name: helm
        tasks_from: reset

- name: Reset Node
  hosts: node
  become: true
  gather_facts: true
  tasks:
    - name: Reset k3s
      ansible.builtin.import_role:
        name: k3s
        tasks_from: reset

- name: Reset Cluster
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Reset longhorn
      ansible.builtin.import_role:
        name: longhorn
        tasks_from: reset
