---
- name: Cluster Reset
  hosts: cluster
  become: true
  gather_facts: true
  serial:
    - 3
    - 5
  vars_prompt:
    - name: prompt_remove_packages
      prompt: Remove installed apt packages? [Y/n]
      default: 'n'
      private: false
  tasks:
    - name: Reset kubernetes
      ansible.builtin.import_role:
        name: k3s
        tasks_from: reset

    - name: Get packages information
      ansible.builtin.package_facts:

    - name: Reset cert-manager chart
      ansible.builtin.import_role:
        name: certmanager
        tasks_from: reset

    - name: Reset cilium chart
      ansible.builtin.import_role:
        name: cilium
        tasks_from: reset

    - name: Reset longhorn chart
      ansible.builtin.import_role:
        name: longhorn
        tasks_from: reset

    - name: Reset prometheus chart
      ansible.builtin.import_role:
        name: prometheus
        tasks_from: reset

    - name: Reset helm
      ansible.builtin.import_role:
        name: helm
        tasks_from: reset
