---
- name: Control Reset
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: reset

- name: Node Reset
  hosts: node
  become: true
  gather_facts: true
  roles:
    - role: reset
