---
- name: Control Plane Reset
  hosts: control
  gather_facts: true
  become: true
  tasks:
    - name: Perform control reset
      ansible.builtin.import_role:
        name: control
        tasks_from: reset
