---
- name: Control Plane Reset
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: reset

- name: Node Reset
  hosts: cerus.lan
  become: true
  gather_facts: true
  roles:
    - role: reset
