---
- name: Charts Upgrade
  hosts: control
  become: true
  gather_facts: true
  tasks:
    - name: Upgrade cilium
      ansible.builtin.import_role:
        name: cilium
        tasks_from: main
      tags:
        - cilium
    - name: Upgrade cert-manager
      ansible.builtin.import_role:
        name: certmanager
        tasks_from: main
      tags:
        - certmanager
