---
- name: Cluster Upgrade
  hosts: cluster
  become: true
  gather_facts: true
  tags: cluster
  tasks:
    - name: Upgrade distribution
      ansible.builtin.import_role:
        name: cluster
        tasks_from: upgrade

- name: Kubernetes Upgrade
  hosts: server
  become: true
  gather_facts: true
  tasks:
    - name: Upgrade Charts
      block:
        - name: Upgrade cert-manager chart
          ansible.builtin.import_role:
            name: certmanager
          tags: certmanager

        - name: Upgrade cilium chart
          ansible.builtin.import_role:
            name: cilium
          tags: cilium

        - name: Upgrade longhorn chart
          ansible.builtin.import_role:
            name: longhorn
          tags: longhorn

        - name: Upgrade prometheus chart
          ansible.builtin.import_role:
            name: prometheus
          tags: prometheus

    - name: Upgrade helm
      ansible.builtin.import_role:
        name: helm
      tags: helm

    - name: Upgrade k3s
      ansible.builtin.import_role:
        name: k3s
        tasks_from: upgrade
      tags: k3s
