---
- name: Get user info
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
  register: user_info

- name: Hush login
  ansible.builtin.file:
    access_time: preserve
    mode: 0644
    modification_time: preserve
    path: "{{ user_info.home }}/.hushlogin"
    state: touch
  become_user: "{{ user_info.name }}"

- name: Set authorized key
  ansible.posix.authorized_key:
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/' + ansible_user_key) }}"
    state: present
    user: "{{ user_info.name }}"
