---
- name: Add helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io

- name: Get user info
  ansible.builtin.user:
    name: "{{ raspios_user }}"
    state: present
  register: user_info

- name: Install helm chart
  kubernetes.core.helm:
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_chart_version }}"
    kubeconfig: "{{ user_info.home }}/.kube/config"
    name: cilium
    namespace: kube-system
    update_repo_cache: true
    values:
      operator.replicas: 1
