---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Install Dependencies
  when: ansible_host in k3s_server_hosts
  block:
    - name: Set binary fact
      ansible.builtin.set_fact:
        binary:
          - org: cilium
            repo: cilium-cli
            version: '{{ cilium_version_cli }}'
            name: cilium-linux-arm64.tar.gz
          - org: cilium
            repo: hubble
            version: '{{ cilium_version_hubble }}'
            name: hubble-linux-arm64.tar.gz
      run_once: true

    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/{{ item.org }}/{{ item.repo }}/releases/download/{{ item.version }}/{{ item.name }}
        checksum: sha256:https://github.com/{{ item.org }}/{{ item.repo }}/releases/download/{{ item.version }}/{{ item.name }}.sha256sum
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
      loop: '{{ binary }}'

    - name: Install binary
      ansible.builtin.unarchive:
        src: /tmp/{{ item.name }}
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      loop: '{{ binary }}'

    - name: Delete archive
      ansible.builtin.file:
        path: /tmp/{{ item.name }}
        state: absent
      loop: '{{ binary }}'

    - name: Add repository
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io

- name: Chart Setup
  when: ansible_host == k3s_server_default_host
  block:
    - name: Install chart
      kubernetes.core.helm:
        chart_ref: cilium/cilium
        chart_version: '{{ cilium_version_chart }}'
        kubeconfig: '{{ k3s_dir_config }}/k3s.yaml'
        name: cilium
        namespace: kube-system
        update_repo_cache: true
        values:
          bgpControlPlane:
            enabled: true
          enableCiliumEndpointSlice: true
          envoy:
            resources:
              limits:
                cpu: 400m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 64Mi
            rollOutPods: true
          envoyConfig:
            enabled: true
          externalIPs:
            enabled: true
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList: '{{ cilium_pod_ip_pool }}'
          hubble:
            relay:
              enabled: true
              rollOutPods: true
            ui:
              enabled: true
              rollOutPods: true
          k8sClientRateLimit:
            burst: 100
            qps: 50
          k8sServiceHost: '{{ k3s_proxy_host }}'
          k8sServicePort: '{{ k3s_proxy_port }}'
          kubeProxyReplacement: true
          l2announcements:
            enabled: true
          operator:
            resources:
              limits:
                cpu: 200m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 64Mi
            rollOutPods: true
          rollOutCiliumPods: true
        wait: true

    - name: Install l2 announcement policy manifest
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumL2AnnouncementPolicy
          metadata:
            name: default-l2-announcement-policy
            namespace: kube-system
          spec:
            externalIPs: true
            interfaces:
              - '{{ k3s_network_interface }}'
            loadBalancerIPs: true
        kubeconfig: '{{ k3s_dir_config }}/k3s.yaml'

    - name: Install loadbalancer ip pool manifest
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumLoadBalancerIPPool
          metadata:
            name: default-pool
            namespace: kube-system
          spec:
            cidrs:
              - cidr: '{{ cilium_loadbalancer_ip_pool }}'
        kubeconfig: '{{ k3s_dir_config }}/k3s.yaml'
