---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts
  tags: always

- name: Install Dependencies
  tags: deps
  when: ansible_host in k3s_server_hosts
  block:
    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/cilium/{{ item[0] }}/releases/download/{{ item[1] }}/{{ item[2] }}.tar.gz
        checksum: sha256:https://github.com/cilium/{{ item[0] }}/releases/download/{{ item[1] }}/{{ item[2] }}.tar.gz.sha256sum
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
      loop:
        - ['cilium-cli', '{{ cilium_cli_version }}', 'cilium-linux-arm64']
        - ['hubble', '{{ cilium_hubble_version }}', 'hubble-linux-arm']
      tags: binary

    - name: Install binary
      ansible.builtin.unarchive:
        src: /tmp/{{ item }}.tar.gz
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      loop:
        - cilium-linux-arm64
        - hubble-linux-arm
      tags: binary

    - name: Delete archive
      ansible.builtin.file:
        path: /tmp/{{ item }}.tar.gz
        state: absent
      loop:
        - cilium-linux-arm64
        - hubble-linux-arm
      tags: binary

    - name: Add repository
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io
      tags: repo

- name: Helm Chart
  tags: chart
  when: ansible_host == k3s_default_host
  block:
    - name: Install chart
      kubernetes.core.helm:
        chart_ref: cilium/cilium
        chart_version: '{{ cilium_chart_version }}'
        kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'
        name: cilium
        namespace: kube-system
        update_repo_cache: true
        values:
          bgpControlPlane:
            enabled: true
          enableCiliumEndpointSlice: true
          externalIPs:
            enabled: true
          hubble:
            relay:
              enabled: true
              rollOutPods: true
            ui:
              enabled: true
              rollOutPods: true
          k8sClientRateLimit:
            burst: 100
            qps: 50
          k8sServiceHost: 127.0.0.1
          k8sServicePort: 6444
          kubeProxyReplacement: true
          l2announcements:
            enabled: true
          rollOutCiliumPods: true
        wait: true

    - name: Install announcement manifest
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumL2AnnouncementPolicy
          metadata:
            name: default-l2-announcement-policy
            namespace: kube-system
          spec:
            externalIPs: true
            loadBalancerIPs: true
        kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'

    - name: Install pool manifest
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumLoadBalancerIPPool
          metadata:
            name: default-pool
            namespace: kube-system
          spec:
            cidrs:
              - cidr: '{{ cilium_ip_pool }}'
        kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'
