---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Download archive
  ansible.builtin.get_url:
    url: https://github.com/cilium/{{ item[0] }}/releases/download/{{ item[1] }}/{{ item[2] }}.tar.gz
    checksum: sha256:https://github.com/cilium/{{ item[0] }}/releases/download/{{ item[1] }}/{{ item[2] }}.tar.gz.sha256sum
    dest: /tmp
    owner: root
    group: root
    mode: '0644'
  loop:
    - ['cilium-cli', '{{ cilium_cli_version }}', 'cilium-linux-arm64']
    - ['hubble', '{{ cilium_hubble_version }}', 'hubble-linux-arm']

- name: Install binary
  ansible.builtin.unarchive:
    src: /tmp/{{ item }}.tar.gz
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  loop:
    - cilium-linux-arm64
    - hubble-linux-arm

- name: Delete archive
  ansible.builtin.file:
    path: /tmp/{{ item }}.tar.gz
    state: absent
  loop:
    - cilium-linux-arm64
    - hubble-linux-arm

- name: Add repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io

- name: Helm Chart
  when: ansible_host == k3s_default_host
  block:
    - name: Install chart
      kubernetes.core.helm:
        chart_ref: cilium/cilium
        chart_version: '{{ cilium_chart_version }}'
        kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'
        name: cilium
        namespace: kube-system
        update_repo_cache: true
        values:
          bgpControlPlane:
            enabled: true
          enableCiliumEndpointSlice: true
          externalIPs:
            enabled: true
          hubble:
            relay:
              enabled: true
              rollOutPods: true
            ui:
              enabled: true
              rollOutPods: true
          k8sClientRateLimit:
            qps: 50
            burst: 100
          l2announcements:
            enabled: true
          rollOutCiliumPods: true
        wait: true

    - name: Install CiliumLoadBalancerIPPool manifest
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumLoadBalancerIPPool
          metadata:
            name: default-pool
            namespace: kube-system
          spec:
            cidrs:
              - cidr: '{{ cilium_ip_pool }}'
        kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'

    - name: Install CiliumL2AnnouncementPolicy manifest
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumL2AnnouncementPolicy
          metadata:
            name: default-l2-announcement-policy
            namespace: kube-system
          spec:
            externalIPs: true
            loadBalancerIPs: true
        kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'
