---
- name: Import role
  ansible.builtin.import_role:
    name: common
    tasks_from: facts

# - name: Delete current binary
#   ansible.builtin.file:
#     path: /usr/local/bin/cilium
#     state: absent

- name: Download archive
  ansible.builtin.get_url:
    url: https://github.com/cilium/cilium-cli/releases/download/{{ cilium_version }}/cilium-linux-arm.tar.gz
    checksum: sha256:https://github.com/cilium/cilium-cli/releases/download/{{ cilium_version }}/cilium-linux-arm.tar.gz.sha256sum
    dest: /tmp
    owner: root
    group: root
    mode: 0644
  notify: Install binary

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Delete archive
  ansible.builtin.file:
    path: /tmp/cilium-linux-arm.tar.gz
    state: absent

- name: Add helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_state: present
    repo_url: https://helm.cilium.io

- name: Install helm chart
  kubernetes.core.helm:
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_chart_version }}"
    kubeconfig: "{{ k3s_conf_dir }}/k3s.yaml"
    name: cilium
    namespace: kube-system
    update_repo_cache: true
    values:
      l7Proxy: false
      operator:
        replicas: 1
    wait: true
  when: ansible_host == k3s_host
