---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Chart Settings
  when: ansible_host == k3s_server_default_host
  block:
    - name: Enable additional features
      kubernetes.core.helm:
        chart_ref: cilium/cilium
        chart_version: '{{ cilium_vars.version.chart }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: cilium
        namespace: kube-system
        reset_values: false
        reuse_values: true
        values:
          dashboards:
            enabled: true
          envoy:
            prometheus:
              serviceMonitor:
                enabled: true
                namespace: kube-system
          hubble:
            metrics:
              dashboards:
                enabled: true
              enabled:
                - dns:query;ignoreAAAA
                - drop
                - http
                - flow
                - icmp
                - port-distribution
                - tcp
              serviceMonitor:
                enabled: true
                namespace: kube-system
            relay:
              prometheus:
                serviceMonitor:
                  enabled: true
                  namespace: kube-system
            tls:
              auto:
                certManagerIssuerRef: cloudflare-cluster-issuer
                method: certmanager
          ingressController:
            enabled: true
            loadbalancerMode: '{{ cilium_vars.ingress_controller.loadbalancer.mode }}'
            service:
              loadBalancerIP: '{{ cilium_vars.ingress_controller.loadbalancer.ip }}'
          operator:
            prometheus:
              enabled: true
              serviceMonitor:
                enabled: true
                namespace: kube-system
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
        wait: true

    - name: Set hubble ui loadbalancer ip
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hubble-ui
            namespace: kube-system
            annotations:
              io.cilium/lb-ipam-ips: '{{ cilium_vars.hubble_ui.loadbalancer.ip }}'
              io.cilium/lb-ipam-sharing-key: hubble-ui
          spec:
            selector:
              k8s-app: hubble-ui
            type: LoadBalancer
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
