---
- name: Import facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - cloudflare
    - k3s

- name: Chart Settings
  when: ansible_host == k3s_server_default_host
  block:
    - name: Enable prometheus metrics
      kubernetes.core.helm:
        chart_ref: cilium/cilium
        chart_version: '{{ cilium_vars.version.chart }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: cilium
        namespace: kube-system
        reset_values: false
        reuse_values: true
        values:
          dashboards:
            enabled: true
          envoy:
            prometheus:
              serviceMonitor:
                enabled: true
          hubble:
            metrics:
              dashboards:
                enabled: true
              enabled:
                - dns:query;ignoreAAAA
                - drop
                - http
                - flow
                - icmp
                - port-distribution
                - tcp
              serviceMonitor:
                enabled: true
            relay:
              prometheus:
                serviceMonitor:
                  enabled: true
          operator:
            prometheus:
              enabled: true
              serviceMonitor:
                enabled: true
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
        wait: true

    - name: Create hubble ui ingress
      kubernetes.core.k8s:
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: hubble-ui
            namespace: kube-system
            annotations:
              cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
              io.cilium/lb-ipam-ips: '{{ cilium_vars.hubble_ui.loadbalancer.ip }}'
              io.cilium/lb-ipam-sharing-key: hubble-ui
          spec:
            ingressClassName: cilium
            rules:
              - host: hubble.{{ cloudflare_vars.ingress.domain }}
                http:
                  paths:
                    - backend:
                        service:
                          name: hubble-ui
                          port:
                            number: 8081
                      path: /
                      pathType: Prefix
            tls:
              - hosts:
                  - hubble.{{ cloudflare_vars.ingress.domain }}
                secretName: cloudflare-tls-hubble-ui
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
