---
- name: Reboot
  ansible.builtin.reboot:
  register: reboot

- name: Reload mail service
  ansible.builtin.systemd_service:
    name: postfix.service
    state: reloaded
    enabled: true
  when: not reboot.changed

- name: Restart unattended upgrades service
  ansible.builtin.systemd_service:
    name: unattended-upgrades.service
    state: restarted
    enabled: true
  when: not reboot.changed
