---
- name: Import role
  ansible.builtin.import_role:
    name: common
    tasks_from: facts

- name: Add helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_state: present
    repo_url: https://charts.longhorn.io

- name: Install helm chart
  kubernetes.core.helm:
    chart_ref: metallb/metallb
    chart_version: "{{ metallb_chart_version }}"
    kubeconfig: "{{ k3s_conf_dir }}/k3s.yaml"
    name: metallb
    namespace: metallb-system
    create_namespace: true
    update_repo_cache: true
    wait: true
  when: ansible_host == k3s_host
