---
- name: Import facts
  ansible.builtin.import_role:
    name: common
    tasks_from: facts

- name: Add helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_state: present
    repo_url: https://charts.longhorn.io

- name: Install helm chart
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    kubeconfig: "{{ k3s_conf_dir }}/k3s.yaml"
    name: longhorn
    namespace: longhorn-system
    create_namespace: true
    update_repo_cache: true
    values:
      service:
        ui:
          loadBalancerIP: "{{ longhorn_loadbalancer_ip }}"
          type: LoadBalancer
    wait: true
  when: ansible_host == k3s_host
