---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Add repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  when: ansible_host in k3s_server_hosts

- name: Chart Setup
  when: ansible_host == k3s_server_default_host
  block:
    - name: Install chart
      kubernetes.core.helm:
        chart_ref: longhorn/longhorn
        chart_version: '{{ longhorn_version_chart }}'
        kubeconfig: '{{ k3s_dir_config }}/k3s.yaml'
        name: longhorn
        namespace: longhorn-system
        create_namespace: true
        update_repo_cache: true
        values:
          defaultSettings:
            nodeDownPodDeletionPolicy: '{{ longhorn_pod_deletion_policy }}'
        wait: true

    - name: Set longhorn-frontend loadbalancer ip
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: longhorn-frontend
            namespace: longhorn-system
            annotations:
              io.cilium/lb-ipam-ips: '{{ longhorn_loadbalancer_ip_frontend }}'
              io.cilium/lb-ipam-sharing-key: longhorn-frontend
          spec:
            selector:
              app: longhorn-ui
            type: LoadBalancer
        kubeconfig: '{{ k3s_dir_config }}/k3s.yaml'
