---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts
  tags: always

- name: Add repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  tags: repo
  when: ansible_host in k3s_server_hosts

- name: Install chart
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    chart_version: '{{ longhorn_chart_version }}'
    kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'
    name: longhorn
    namespace: longhorn-system
    create_namespace: true
    update_repo_cache: true
    values:
      defaultSettings:
        nodeDownPodDeletionPolicy: '{{ longhorn_pod_deletion_policy }}'
      service:
        ui:
          type: LoadBalancer
    wait: true
  tags: chart
  when: ansible_host == k3s_default_host
