---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Remove repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_state: absent
  when: ansible_host in k3s_server_hosts

- name: Remove package
  ansible.builtin.apt:
    name: open-iscsi
    state: absent
    autoremove: true
  when: remove_packages in ['y', 'Y']

- name: Remove files
  ansible.builtin.file:
    name: /var/lib/longhorn
    state: absent
