---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Remove repository
  kubernetes.core.helm_repository:
    name: '{{ longhorn_vars.kubernetes.helm.repository.name }}'
    repo_state: absent
  when:
    - ansible_host in k3s_server_hosts
    - "'helm' in ansible_facts.packages"

- name: Remove file
  ansible.builtin.file:
    name: /var/lib/longhorn
    state: absent
