---
- name: Test Raspberry Pi CPU
  ansible.builtin.command:
    cmd: egrep 'BCM2708|BCM2709|BCM2835|BCM2836' /proc/cpuinfo
  changed_when: cpuinfo.rc != 0
  register: cpuinfo

- name: Test Raspberry Pi model
  ansible.builtin.command:
    cmd: grep 'Raspberry Pi' /proc/device-tree/model
  changed_when: model.rc != 0
  register: model

- name: Set Raspberry Pi fact
  ansible.builtin.set_fact:
    raspberry_pi: true
  when:
    - ansible_facts.lsb.id | default('') == pi_lsbid
    - ansible_facts.machine | default('') == 'aarch64'
    - cpuinfo.rc == 0 or model.rc == 0
