---
- name: Add KUBECONFIG variable to environment
  ansible.builtin.lineinfile:
    line: KUBECONFIG={{ k3s_conf_dir }}/k3s.yaml
    path: /etc/environment
    regexp: ^KUBECONFIG
    state: present

- name: Create symlinks
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - crictl
    - ctr
    - kubectl

- name: Token
  when: k3s_token | length == 0
  block:
    - name: Wait for token creation
      ansible.builtin.wait_for:
        path: "{{ k3s_lib_dir }}/server/node-token"

    - name: Read token
      ansible.builtin.slurp:
        path: "{{ k3s_lib_dir }}/server/node-token"
      register: node_token

    - name: Set token fact
      ansible.builtin.set_fact:
        token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
      run_once: true

- name: Get user info
  ansible.builtin.user:
    name: "{{ raspios_user }}"
    state: present
  register: user_info

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ user_info.home }}/.kube"
    owner: "{{ user_info.name }}"
    group: "{{ user_info.name }}"
    mode: "755"
    state: directory

- name: Copy configuration file
  ansible.builtin.copy:
    src: "{{ k3s_conf_dir }}/k3s.yaml"
    dest: "{{ user_info.home }}/.kube/config"
    owner: "{{ user_info.name }}"
    group: "{{ user_info.name }}"
    mode: "600"
    remote_src: true

- name: Replace localhost with control host
  ansible.builtin.command:
    cmd: kubectl config set-cluster default
          --server=https://{{ ansible_host }}:6443
          --kubeconfig={{ user_info.home }}/.kube/config
  changed_when: true
