---
- name: Add KUBECONFIG variable to environment
  ansible.builtin.lineinfile:
    line: KUBECONFIG={{ k3s_conf_dir }}/k3s.yaml
    path: /etc/environment
    regexp: ^KUBECONFIG
    state: present

- name: Create symlinks
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/{{ name }}
    state: link
  loop_control:
    loop_var: link
  vars:
    name: "{{ link }}"
  with_items:
    - crictl
    - ctr
    - kubectl

- name: Wait for token creation
  ansible.builtin.wait_for:
    path: "{{ k3s_data_dir }}/server/node-token"
  when: k3s_token | length == 0

- name: Read token
  ansible.builtin.slurp:
    path: "{{ k3s_data_dir }}/server/node-token"
  register: node_token
  when: k3s_token | length == 0

- name: Set token fact
  ansible.builtin.set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
  when: k3s_token | length == 0
