---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Install Dependencies
  when: ansible_host in k3s_server_hosts
  block:
    - name: Set binary fact
      ansible.builtin.set_fact:
        binary:
          org: bitnami-labs
          repo: sealed-secrets
          version: '{{ sealedsecrets_vars.kubeseal.version }}'
          checksums: 'sealed-secrets_{{ sealedsecrets_vars.kubeseal.version[1:] }}_checksums.txt'
          name: '{{ sealedsecrets_vars.kubeseal.name }}'
      run_once: true

    - name: Set checksums fact
      ansible.builtin.uri:
        url: https://github.com/{{ binary['org'] }}/{{ binary['repo'] }}/releases/download/{{ binary['version'] }}/{{ binary['checksums'] }}
        return_content: true
      register: checksums
      run_once: true

    - name: Set sha256 checksum fact
      ansible.builtin.set_fact:
        sha256_checksum: "{{ item.split(' ')[0] }}"
      loop: "{{ checksums.content.split('\n') }}"
      when: sealedsecrets_vars.kubeseal.name in item
      run_once: true

    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/{{ binary['org'] }}/{{ binary['repo'] }}/releases/download/{{ binary['version'] }}/{{ binary['name'] }}
        checksum: sha256:{{ sha256_checksum }}
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Install binary
      ansible.builtin.unarchive:
        src: /tmp/{{ binary['name'] }}
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
        remote_src: true

    - name: Delete archive
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - /tmp/{{ binary['name'] }}
        - /usr/local/bin/LICENSE
        - /usr/local/bin/README.md

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ sealedsecrets_vars.kubernetes.helm.repository.name }}'
        repo_url: '{{ sealedsecrets_vars.kubernetes.helm.repository.url }}'

- name: Install chart
  kubernetes.core.helm:
    chart_ref: '{{ sealedsecrets_vars.kubernetes.helm.repository.name }}/{{ sealedsecrets_vars.kubernetes.helm.chart.name }}'
    chart_version: '{{ sealedsecrets_vars.kubernetes.helm.chart.version }}'
    kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
    name: '{{ sealedsecrets_vars.kubernetes.helm.chart.name }}'
    namespace: '{{ sealedsecrets_vars.kubernetes.namespace }}'
    update_repo_cache: true
    wait: true
  register: result
  delay: 1
  retries: 3
  until: result is not failed
  when: ansible_host == k3s_server_default_host
