---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Install Dependencies
  when: ansible_host in k3s_server_hosts
  block:
    - name: Set binary fact
      ansible.builtin.set_fact:
        binary:
          org: bitnami-labs
          repo: sealed-secrets
          version: '{{ sealedsecrets_version_kubeseal }}'
          checksums: 'sealed-secrets_{{ sealedsecrets_version_kubeseal[1:] }}_checksums.txt'
          name: 'kubeseal-{{ sealedsecrets_version_kubeseal[1:] }}-linux-arm64.tar.gz'
      run_once: true

    - name: Set checksums fact
      ansible.builtin.uri:
        url: https://github.com/{{ binary['org'] }}/{{ binary['repo'] }}/releases/download/{{ binary['version'] }}/{{ binary['checksums'] }}
        return_content: true
      register: checksums
      run_once: true

    - name: Set sha256 checksum fact
      ansible.builtin.set_fact:
        sha256_checksum: "{{ item.split(' ')[0] }}"
      loop: "{{ checksums.content.split('\n') }}"
      when: "'linux-arm64' in item"
      run_once: true

    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/{{ binary['org'] }}/{{ binary['repo'] }}/releases/download/{{ binary['version'] }}/{{ binary['name'] }}
        checksum: sha256:{{ sha256_checksum }}
        dest: /tmp
        owner: root
        group: root
        mode: '0644'

    - name: Install binary
      ansible.builtin.unarchive:
        src: /tmp/{{ binary['name'] }}
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
        remote_src: true

    - name: Delete archive
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - /tmp/{{ binary['name'] }}
        - /usr/local/bin/LICENSE
        - /usr/local/bin/README.md

    - name: Add repository
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: https://bitnami-labs.github.io/sealed-secrets

- name: Install chart
  kubernetes.core.helm:
    chart_ref: sealed-secrets/sealed-secrets
    chart_version: '{{ sealedsecrets_version_chart }}'
    kubeconfig: '{{ k3s_dir_config }}/k3s.yaml'
    name: sealed-secrets
    namespace: kube-system
    update_repo_cache: true
    wait: true
  when: ansible_host == k3s_server_default_host
