---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts
  tags: always

- name: Install Dependencies
  tags: deps
  when: ansible_host in k3s_server_hosts
  block:
    - name: Set link fact
      ansible.builtin.set_fact:
        repo_link: ['sealed-secrets', '{{ sealedsecrets_version }}', '{{ sealedsecrets_kubeseal_filename }}']
      tags: binary

    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/bitnami-labs/{{ repo_link[0] }}/releases/download/{{ repo_link[1] }}/{{ repo_link[2] }}.tar.gz
        checksum: md5:https://github.com/bitnami-labs/{{ repo_link[0] }}/releases/download/{{ repo_link[1] }}/{{ repo_link[2] }}.tar.gz.sig
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
      tags: binary

    - name: Install binary
      ansible.builtin.unarchive:
        src: /tmp/{{ sealedsecrets_kubeseal_filename }}.tar.gz
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      tags: binary

    - name: Delete archive
      ansible.builtin.file:
        path: /tmp/{{ sealedsecrets_kubeseal_filename }}.tar.gz
        state: absent
      tags: binary

    - name: Add repository
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: https://bitnami-labs.github.io/sealed-secrets
      tags: repo

- name: Install chart
  kubernetes.core.helm:
    chart_ref: sealed-secrets/sealed-secrets
    chart_version: '{{ sealedsecrets_chart_version }}'
    kubeconfig: '{{ k3s_conf_dir }}/k3s.yaml'
    name: sealed-secrets
    namespace: kube-system
    update_repo_cache: true
    wait: true
  tags: chart
  when: ansible_host == k3s_default_host
