---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Install Dependencies
  when: ansible_host in k3s_server_hosts
  block:
    - name: Set binary fact
      ansible.builtin.set_fact:
        binary:
          name: sealed-secrets
          org: bitnami-labs
          version: '{{ sealedsecrets_version_kubeseal }}'
          tarball: 'kubeseal-{{ sealedsecrets_version_kubeseal[1:] }}-linux-arm64.tar.gz'

    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/{{ binary['org'] }}/{{ binary['name'] }}/releases/download/{{ binary['version'] }}/{{ binary['tarball'] }}
        # checksum: sha256:https://github.com/{{ binary['org'] }}/{{ binary['name'] }}/releases/download/{{ binary['version'] }}/{{ binary['tarball'] }}.sig
        dest: /tmp
        owner: root
        group: root
        mode: '0644'

    - name: Install binary
      ansible.builtin.unarchive:
        src: /tmp/{{ binary['tarball'] }}
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
        remote_src: true

    - name: Delete archive
      ansible.builtin.file:
        path: /tmp/{{ item }}
        state: absent
      loop:
        - "{{ binary['tarball'] }}"
        - LICENSE
        - README.md

    - name: Add repository
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: https://bitnami-labs.github.io/sealed-secrets

- name: Install chart
  kubernetes.core.helm:
    chart_ref: sealed-secrets/sealed-secrets
    chart_version: '{{ sealedsecrets_version_chart }}'
    kubeconfig: '{{ k3s_dir_config }}/k3s.yaml'
    name: sealed-secrets
    namespace: kube-system
    update_repo_cache: true
    wait: true
  when: ansible_host == k3s_server_default_host
