---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Remove Dependencies
  when:
    - ansible_host in k3s_server_hosts
    - "'helm' in ansible_facts.packages"
  block:
    - name: Remove repository
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_state: absent

    - name: Remove file
      ansible.builtin.file:
        name: /usr/local/bin/kubeseal
        state: absent
