---
- name: Install binary
  ansible.builtin.unarchive:
    src: /tmp/{{ item }}-linux-arm.tar.gz
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "755"
    remote_src: true
  loop:
    - cilium
    - hubble
