---
cilium_loadbalancer_ip_hubble: 192.168.4.18
cilium_loadbalancer_ip_pool: '192.168.4.16/28'
cilium_pod_ip_pool: '10.42.0.0/16'
cilium_version_chart: v1.14.5
cilium_version_cli: v0.15.19
cilium_version_hubble: v0.12.3
