---
- name: Enable memory cgroup
  ansible.builtin.lineinfile:
    backrefs: true
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_memory=1\b).*)$'
    line: '\g<1> cgroup_memory=1 cgroup_enable=memory'
    state: present
  changed_when: cmdline is changed
  notify: Perform reboot
  register: cmdline

- name: Upgrade all packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Remove no longer required dependencies
  ansible.builtin.apt:
    autoremove: true

- name: Disable bluetooth and wifi services
  ansible.builtin.systemd:
    enabled: false
    name: '{{ name }}.service'
  loop_control:
    loop_var: service
  vars:
    name: '{{ service }}'
  with_items:
    - bluetooth
    - hciuart
    - wpa_supplicant

- name: Boot from USB if available
  ansible.builtin.command: raspi-config nonint do_boot_behaviour B2
  changed_when: false

- name: Wait for network connection on boot
  ansible.builtin.command: raspi-config nonint do_boot_wait 0
  changed_when: false

- name: Update bootloader firmware
  ansible.builtin.command: rpi-eeprom-update -ad
  changed_when: eeprom_update.stdout.find('updates pending') != -1
  notify: Perform reboot
  register: eeprom_update

- name: Check reboot status
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  changed_when: reboot.stat.exists
  notify: Perform reboot
  register: reboot
