---
- name: Add KUBECONFIG variable to environment
  ansible.builtin.lineinfile:
    line: KUBECONFIG={{ k3s_config_dir }}/k3s.yaml
    path: /etc/environment
    regexp: ^KUBECONFIG=
    state: present

- name: Create k3s configuration directory
  ansible.builtin.file:
    path: '{{ k3s_config_dir }}'
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Copy k3s configuration file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: '{{ k3s_config_dir }}/config.yaml'
    mode: 0600
    owner: root
    group: root

- name: Copy k3s service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    mode: 0644
    owner: root
    group: root

- name: Enable and check k3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    enabled: true
    state: restarted

- name: Wait for token creation
  ansible.builtin.wait_for:
    path: '{{ k3s_data_dir }}/server/node-token'

# - name: Register token file permissions
#   ansible.builtin.stat:
#     path: '{{ k3s_data_dir }}/server/node-token'
#   register: token_permissions

# - name: Change token file permissions
#   ansible.builtin.file:
#     path: '{{ k3s_data_dir }}/server/node-token'
#     mode: 0644

- name: Read token
  ansible.builtin.slurp:
    path: '{{ k3s_data_dir }}/server/node-token'
  register: node_token

- name: Store token
  ansible.builtin.set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

# - name: Restore token file permissions
#   ansible.builtin.file:
#     path: '{{ k3s_data_dir }}/server/node-token'
#     mode: '{{ token_permissions.stat.mode }}'

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
