---
- name: Reboot
  ansible.builtin.reboot:
    post_reboot_delay: 30

- name: Start service
  ansible.builtin.systemd_service:
    name: '{{ k3s_service_name }}.service'
    state: started
    daemon_reload: true
    enabled: true

- name: Stop service
  ansible.builtin.systemd_service:
    name: '{{ k3s_service_name }}.service'
    state: stopped
    enabled: false
  failed_when:
    - service.failed == true
    - service.msg.find('Could not find the requested service') == -1
  register: service
