---
- name: Reboot
  ansible.builtin.reboot:

- name: Start service
  ansible.builtin.systemd_service:
    name: '{{ k3s_service_name }}.service'
    state: started
    daemon_reload: true
    enabled: true
  register: service
  until: service.status.ActiveState == 'active'
  delay: 5
  retries: 5

- name: Stop service
  ansible.builtin.systemd_service:
    name: '{{ k3s_service_name }}.service'
    state: stopped
    enabled: false
  failed_when:
    - service.failed == true
    - service.msg.find('Could not find the requested service') == -1
  register: service
