---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Install package
  ansible.builtin.apt:
    name: open-iscsi
    autoremove: true
    force_apt_get: true
    update_cache: true

- name: Install k3s binary
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: '0755'
  notify: Start service

- name: Create configuration directory
  ansible.builtin.file:
    path: '{{ k3s_conf_dir }}'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Create configuration file
  ansible.builtin.template:
    src: config.j2
    dest: '{{ k3s_conf_dir }}/config.yaml'
    owner: root
    group: root
    mode: '0600'
  notify: Start service

- name: Create service file
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/{{ k3s_service_name }}.service
    owner: root
    group: root
    mode: '0644'
  notify: Start service

- name: Create service environment file
  ansible.builtin.file:
    access_time: preserve
    owner: root
    group: root
    mode: '0600'
    modification_time: preserve
    path: /etc/systemd/system/{{ k3s_service_name }}.service.env
    state: touch
  notify: Start service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

# - name: Traefik Configuration
#   when: ansible_host in k3s_control_hosts
#   block:
#     - name: Wait for directory creation
#       ansible.builtin.wait_for:
#         path: '{{ k3s_lib_dir }}/server/manifests'

#     - name: Create configuration file
#       ansible.builtin.template:
#         src: traefik.j2
#         dest: '{{ k3s_lib_dir }}/server/manifests/traefik-config.yaml'
#         owner: root
#         group: root
#         mode: '0600'
#       notify: Start service

# - name: Flush handlers
#   ansible.builtin.meta: flush_handlers
