---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml
  tags: always

- name: Stop service
  ansible.builtin.assert:
    quiet: true
    that: true
  changed_when: true
  notify:
    - Stop service
    - Reboot
  tags: always

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: always

- name: Kill processes
  ansible.builtin.shell: |
    set -eo pipefail
    if [ -d {{ item }} ]; then
      for i in $(ps -eo pid= -o args= | grep {{ item }} | grep -v grep | tr -s ' ' | cut -d ' ' -f 2); do
        kill -KILL $i
      done
      for j in $(grep {{ item }} /proc/self/mounts | cut -d ' ' -f 2); do
        umount -f $j
      done
    fi
  args:
    executable: /bin/bash
  changed_when: script.rc == 0
  loop:
    - /run/k3s
    - /var/lib/cni
    - /var/lib/kubelet
    - /var/lib/rancher
  register: script
  tags: always

- name: Get user info
  ansible.builtin.user:
    name: '{{ pi_user }}'
  register: user_info
  tags: always

- name: Remove files
  ansible.builtin.file:
    name: '{{ item }}'
    state: absent
  loop:
    - '{{ user_info.home }}/.kube'
    - '{{ k3s_conf_dir }}'
    - /etc/systemd/system/{{ k3s_service_name }}.service
    - /etc/systemd/system/{{ k3s_service_name }}.service.env
    - /run/k3s
    - /usr/local/bin/crictl
    - /usr/local/bin/ctr
    - /usr/local/bin/k3s
    - /usr/local/bin/kubectl
    - /var/lib/cni
    - /var/lib/kubelet
    - /var/lib/rancher
  tags: always
