---
- name: Add variable to environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: KUBECONFIG={{ k3s_conf_dir }}/k3s.yaml
    regexp: ^KUBECONFIG

- name: Create symlinks
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - crictl
    - ctr
    - kubectl

- name: Set Token
  when: k3s_token | length == 0
  block:
    - name: Wait for token creation
      ansible.builtin.wait_for:
        path: '{{ k3s_lib_dir }}/server/node-token'

    - name: Read token
      ansible.builtin.slurp:
        path: '{{ k3s_lib_dir }}/server/node-token'
      register: node_token

    - name: Set token fact
      ansible.builtin.set_fact:
        token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
      run_once: true

- name: Get user info
  ansible.builtin.user:
    name: '{{ raspberry_pi_user }}'
  register: user_info

- name: Create configuration directory
  ansible.builtin.file:
    path: '{{ user_info.home }}/.kube'
    owner: '{{ user_info.name }}'
    group: '{{ user_info.name }}'
    mode: '0755'
    state: directory

- name: Copy configuration file
  ansible.builtin.copy:
    src: '{{ k3s_conf_dir }}/k3s.yaml'
    dest: '{{ user_info.home }}/.kube/config'
    owner: '{{ user_info.name }}'
    group: '{{ user_info.name }}'
    mode: '0600'
    remote_src: true

- name: Set host
  ansible.builtin.command:
    cmd: kubectl config set-cluster default
          --kubeconfig={{ user_info.home }}/.kube/config
          --server=https://{{ ansible_host }}:{{ k3s_api_port }}
  changed_when: true
