---
- name: Add variable to environment
  ansible.builtin.lineinfile:
    line: KUBECONFIG={{ k3s_conf_dir }}/k3s.yaml
    path: /etc/environment
    regexp: ^KUBECONFIG

- name: Create symlinks
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - crictl
    - ctr
    - kubectl

- name: Set Token
  when: k3s_token | length == 0
  block:
    - name: Wait for token creation
      ansible.builtin.wait_for:
        path: '{{ k3s_lib_dir }}/server/node-token'

    - name: Read token
      ansible.builtin.slurp:
        path: '{{ k3s_lib_dir }}/server/node-token'
      register: node_token

    - name: Set token fact
      ansible.builtin.set_fact:
        token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
      run_once: true

- name: Get user info
  ansible.builtin.user:
    name: '{{ pi_user }}'
  register: user_info

- name: Create configuration directory
  ansible.builtin.file:
    path: '{{ user_info.home }}/.kube'
    owner: '{{ user_info.name }}'
    group: '{{ user_info.name }}'
    mode: '0755'
    state: directory

- name: Copy configuration file
  ansible.builtin.copy:
    src: '{{ k3s_conf_dir }}/k3s.yaml'
    dest: '{{ user_info.home }}/.kube/config'
    owner: '{{ user_info.name }}'
    group: '{{ user_info.name }}'
    mode: '0600'
    remote_src: true

- name: Set host
  ansible.builtin.command:
    cmd: kubectl config set-cluster default
          --kubeconfig={{ user_info.home }}/.kube/config
          --server=https://{{ ansible_host }}:6443
  changed_when: true

# https://github.com/k3s-io/k3s/issues/5103#issuecomment-1842151021
# kubectl -n kube-system delete helmcharts.helm.cattle.io traefik
# - name: Disable Traefik
#   when: ansible_host in k3s_server_hosts
#   block:
#     - name: Wait for directory creation
#       ansible.builtin.wait_for:
#         path: '{{ k3s_lib_dir }}/server/manifests'

#     - name: Create manifest
#       ansible.builtin.file:
#         path: '{{ k3s_lib_dir }}/server/manifests/traefik.yaml.skip'
#         state: touch
#         owner: root
#         group: root
#         mode: '0644'

# - name: Flush handlers
#   ansible.builtin.meta: flush_handlers
