---
- name: Start service
  ansible.builtin.systemd:
    name: "{{ k3s_service }}.service"
    daemon_reload: true
    enabled: true
    state: restarted

- name: Stop service
  ansible.builtin.systemd:
    name: "{{ k3s_service }}.service"
    daemon_reload: true
    enabled: false
    state: stopped
