---
- name: Test for raspberry pi /proc/cpuinfo
  ansible.builtin.command: egrep 'BCM2708|BCM2709|BCM2835|BCM2836' /proc/cpuinfo
  changed_when: false
  failed_when: false
  register: cpuinfo

- name: Test for raspberry pi /proc/device-tree/model
  ansible.builtin.command: grep 'Raspberry Pi' /proc/device-tree/model
  changed_when: false
  failed_when: false
  register: model

- name: Set raspberry_pi fact to true
  ansible.builtin.set_fact:
    raspberry_pi: true
  when:
    cpuinfo.rc == 0 or model.rc == 0

- name: Set detected_distribution to Raspbian
  ansible.builtin.set_fact:
    detected_distribution: Raspbian
  when:
    - raspberry_pi | default(false)
    - (ansible_facts.lsb.id | default('') == "Raspbian" or
       ansible_facts.lsb.description | default('') is match('[Rr]aspbian.*')

- name: Set detected_distribution_major_version
  ansible.builtin.set_fact:
    detected_distribution_major_version: "{{ ansible_facts.lsb.major_release }}"
  when:
    - detected_distribution | default('') == "Raspbian"

- name: Execute OS related tasks on the Raspberry Pi
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "prereq/{{ detected_distribution }}-{{ detected_distribution_major_version }}.yaml"
    - "prereq/{{ detected_distribution }}.yaml"
    - "prereq/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "prereq/{{ ansible_distribution }}.yaml"
    - "prereq/default.yaml"
  when:
    - raspberry_pi | default(false)
