---
- name: Import facts
  ansible.builtin.import_role:
    name: common
    tasks_from: facts

- name: Stop service
  ansible.builtin.assert:
    quiet: true
    that: true
  changed_when: true
  notify:
    - Perform reboot
    - Stop service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Files cleanup
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ k3s_conf_dir }}"
    - /etc/systemd/system/{{ k3s_service }}.service
    - /etc/systemd/system/{{ k3s_service }}.service.env
    - /usr/local/bin/k3s
    - /var/lib/cni
    - /var/lib/kubelet
    - /var/lib/longhorn
    - /var/lib/rancher
