---
- name: Import facts
  ansible.builtin.import_role:
    name: common
    tasks_from: facts

- name: Stop service
  ansible.builtin.assert:
    quiet: true
    that: true
  changed_when: true
  notify:
    - Stop service
    - Perform reboot

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Get user info
  ansible.builtin.user:
    name: "{{ raspios_user }}"
    state: present
  register: user_info

- name: Files cleanup
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ user_info.home }}/.kube"
    - "{{ common_k3s_conf_dir }}"
    - /etc/systemd/system/{{ k3s_service }}.service
    - /etc/systemd/system/{{ k3s_service }}.service.env
    - /usr/local/bin/k3s
    - /var/lib/cni
    - /var/lib/kubelet
    - /var/lib/longhorn
    - /var/lib/rancher

- name: Variables cleanup
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: ^KUBECONFIG
    state: absent
