---
- name: Cluster Provisioning
  when: raspberry_pi | default(false)
  block:
    - name: Set boot from USB if available
      ansible.builtin.command:
        cmd: raspi-config nonint do_boot_behaviour B2
      changed_when: boot_behaviour.stdout | length > 0
      register: boot_behaviour

    - name: Set wifi country code
      ansible.builtin.command:
        cmd: raspi-config nonint do_wifi_country {{ cluster_country_code }}
      changed_when: wifi_country.stdout | length > 0
      register: wifi_country

    - name: Disable bluetooth service
      ansible.builtin.systemd_service:
        enabled: false
        name: '{{ item }}.service'
      loop:
        - bluetooth
        - hciuart
      when: cluster_disable_service_bluetooth | default(false)

    - name: Disable wifi service
      ansible.builtin.systemd_service:
        enabled: false
        name: wpa_supplicant.service
      when: cluster_disable_service_wifi | default(false)

    - name: Enable memory cgroup
      ansible.builtin.lineinfile:
        backrefs: true
        path: /boot/cmdline.txt
        regexp: ^((?!.*\bcgroup_memory=1\b).*)$
        line: \g<1> cgroup_memory=1 cgroup_enable=memory
      notify: Reboot
      register: cmdline

    - name: Upgrade distribution
      ansible.builtin.import_tasks:
        file: upgrade.yaml
