---
- name: Import validation tasks
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Import user tasks
  ansible.builtin.import_tasks:
    file: user.yaml

- name: Cluster Provisioning
  when: raspberry_pi | default(false)
  block:
    - name: Cluster Configuration
      ansible.builtin.import_tasks:
        file: configuration.yaml
      notify: Reboot

    - name: Device Configuration
      ansible.builtin.import_tasks:
        file: device.yaml

    - name: Distribution Upgrade
      ansible.builtin.import_tasks:
        file: upgrade.yaml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Trim disks
  ansible.builtin.command:
    cmd: fstrim -v /
  changed_when: command.stdout.find('trimmed') != -1
  register: command
  when: disk_trim in ['y', 'Y']
