---
- name: Set device id
  ansible.builtin.command:
    cmd: lsusb -s {{ cluster_device_id }}
  changed_when: device_id.stdout.find(cluster_device_name) != -1
  register: device_id

- name: Set device attributes
  ansible.builtin.set_fact:
    attributes: "{{ device_id.stdout | regex_search('ID\\s+(.*)\\s+' + cluster_device_name, '\\1') | join | trim | split(':') }}"

- name: Enable Trim
  when: attributes is iterable and (attributes | length == 2)
  block:
    - name: Set disk provisioning rule
      ansible.builtin.set_fact:
        provisioning_rule:
          - ACTION=="add|change"
          - ATTRS{idVendor}=="{{ attributes[0] }}"
          - ATTRS{idProduct}=="{{ attributes[1] }}"
          - SUBSYSTEM=="scsi_disk"
          - ATTR{provisioning_mode}="unmap"

    - name: Create disk provisioning rule
      ansible.builtin.lineinfile:
        line: "{{ provisioning_rule | join(', ') }}"
        path: /etc/udev/rules.d/10-provisioning.rules
        regexp: ^ACTION
        owner: root
        group: root
        mode: '0644'
        create: true
      notify: Reboot

    - name: Start fstrim.timer
      ansible.builtin.systemd_service:
        name: fstrim.timer
        state: started
        enabled: true
      notify: Reboot
