---
- name: Get user info
  ansible.builtin.user:
    name: '{{ pi_user }}'
  register: user_info

- name: Hush login
  ansible.builtin.file:
    access_time: preserve
    group: '{{ user_info.name }}'
    owner: '{{ user_info.name }}'
    mode: '0644'
    modification_time: preserve
    path: '{{ user_info.home }}/.hushlogin'
    state: touch

- name: Set authorized key
  ansible.posix.authorized_key:
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/' + pi_user_key) }}"
    user: '{{ user_info.name }}'
