---
- name: Validate trim disks prompt
  ansible.builtin.assert:
    that: prompt_trim_device in ['n', 'N', 'y', 'Y']
    fail_msg: 'Valid entries: n, N, y, Y'
    quiet: true

- name: Get Raspberry Pi model
  ansible.builtin.command:
    cmd: grep 'Raspberry Pi' /proc/device-tree/model
  changed_when: raspberry_pi_model.rc != 0
  register: raspberry_pi_model

- name: Set Raspberry Pi fact
  ansible.builtin.set_fact:
    raspberry_pi: true
  when:
    - ansible_facts.lsb.id == 'Ubuntu'
    - ansible_facts.lsb.release is version('20.10', '>=')
    - ansible_facts.machine == 'aarch64'
    - raspberry_pi_model.rc == 0
