---
- name: Set control fact
  ansible.builtin.set_fact:
    k3s_control: "{{ groups['control'] }}"
  run_once: true

- name: Set agent fact
  ansible.builtin.set_fact:
    k3s_agent: "{{ 'agent' if ansible_host not in k3s_control else 'server' }}"
  run_once: true

- name: Set high-availability fact
  ansible.builtin.set_fact:
    k3s_ha: "{{ (k3s_control | length > 1) | default(false) }}"
  run_once: true

- name: Set host fact
  ansible.builtin.set_fact:
    k3s_host: "{{ hostvars[k3s_control[0]]['ansible_host'] | default(k3s_control[0]) }}"
  run_once: true

- name: Set service fact
  ansible.builtin.set_fact:
    k3s_service: k3s{{ '-agent' if ansible_host not in k3s_control }}
  run_once: true

- name: Set token fact
  ansible.builtin.set_fact:
    k3s_token: "{{ hostvars[k3s_control[0]]['token'] | default('') }}"
  run_once: true
