---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Install open-iscsi package
  ansible.builtin.apt:
    name: open-iscsi
    state: present
    autoremove: true
    update_cache: true

- name: Install k3s binary
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  notify: Start service

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ k3s_conf_dir }}"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Create configuration file
  ansible.builtin.template:
    src: config.j2
    dest: "{{ k3s_conf_dir }}/config.yaml"
    mode: 0600
    owner: root
    group: root
  notify: Start service

- name: Create service file
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/{{ k3s_service }}.service
    mode: 0644
    owner: root
    group: root
  notify: Start service

- name: Create service environment file
  ansible.builtin.file:
    access_time: preserve
    mode: 0600
    modification_time: preserve
    path: /etc/systemd/system/{{ k3s_service }}.service.env
    state: touch
  notify: Start service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
