---
- name: Import facts
  ansible.builtin.import_role:
    name: common
    tasks_from: facts

- name: Update ingress route
  kubernetes.core.k8s:
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: traefik-dashboard
        namespace: kube-system
      spec:
        entryPoints:
          - traefik
        routes:
          - match: Host(`192.168.4.10`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            kind: Rule
            services:
              - kind: TraefikService
                name: api@internal
    kubeconfig: "{{ k3s_conf_dir }}/k3s.yaml"
    state: present
  when: ansible_host == k3s_host
