---
k3s_vars:
  api:
    host: 192.168.4.10
    port: 6443
  cluster:
    dns: 10.43.0.10
    domain: cluster.local
  controlplane:
    tainted: true
  directory:
    config: /etc/rancher/k3s
    lib: /var/lib/rancher/k3s
  loadbalancer:
    enabled: true
    server:
      host: 127.0.0.1
      port: 6444
  network:
    interface: eth0
  service:
    agent_args: ''
    server_args: ''
  version:
    controller: v0.13.2
    kubectl: v1.29.1
    release: v1.29.1+k3s2
