---
- name: Install binary
  ansible.builtin.unarchive:
    src: /tmp/helm-{{ helm_version }}-linux-arm64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: 0755
    remote_src: true
