---
- name: Stop k3s service
  ansible.builtin.systemd:
    name: k3s-node.service
    state: stopped
    enabled: false

- name: Kill running shims
  ansible.builtin.command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: pkill.rc == 0
  register: pkill

- name: Umount k3s filesystems
  ansible.builtin.include_tasks: umount.yaml
  with_items:
    - '{{ k3s_data_dir }}'
    - /run/k3s
    - /run/netns
    - /var/lib/kubelet
  loop_control:
    loop_var: mounted_fs

- name: Remove k3s related data
  ansible.builtin.file:
    name: '{{ item }}'
    state: absent
  with_items:
    - '{{ k3s_conf_dir }}'
    - '{{ k3s_data_dir }}'
    - /etc/systemd/system/k3s-node.service
    - /usr/local/bin/k3s
    - /var/lib/kubelet

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
